# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-22 10:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20160719_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='id_sort',
            field=models.IntegerField(default=0),
        ),
    ]
