# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-25 07:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20160722_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='publish',
            field=models.BooleanField(default=True),
        ),
    ]
