# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-19 10:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='title',
            field=models.CharField(default='about', max_length=255, unique=True),
        ),
    ]
